apiVersion: v1
data: {}
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 5m
    route:
      group_by: ['instance']
      group_wait: 10m
      group_interval: 10s
      repeat_interval: 1m
      receiver: 'PrometheusAlert'
    receivers:
    - name: 'PrometheusAlert'
      webhook_configs:
      - url: 'https://prometheusalert.zoomex.co/prometheusalert?type=fs&tpl=prometheus-fs&fsurl=https://open.larksuite.com/open-apis/bot/v2/hook/3040e986-fa9e-498b-9a2a-c22b66668f0e'
